export type Locale = "et" | "en" | "ru";

export const locales: { code: Locale; label: string }[] = [
  { code: "et", label: "EST" },
  { code: "en", label: "ENG" },
  { code: "ru", label: "РУС" },
];

export const defaultLocale: Locale = "et";

export interface FeatureItem { title: string; desc: string }
export interface FaqItem { q: string; a: string }
export interface ReviewItem { name: string; role: string; rating: number; text: string; date: string }

export interface Dictionary {
  nav: { links: string[]; cta: string };
  hero: { eyebrow: string; title: string; subtitle: string; ctaPrimary: string; ctaSecondary: string; phoneLabel: string; detailsLabel: string; details: string[] };
  intro: { eyebrow: string; title: string; paragraphs: string[]; photoAlts: string[]; photoCaptions: string[]; journeyTitle: string; journey: FeatureItem[] };
  suitedFor: { title: string; items: string[] };
  features: { eyebrow: string; title: string; subtitle: string; adaptabilityTitle: string; adaptabilityText: string; stages: string[]; timelineStart: string; timelineEnd: string; items: FeatureItem[] };
  gallery: { eyebrow: string; title: string; subtitle: string; storySubtitle: string; storyNote: string; curatedCaptions: string[]; curatedAlts: string[]; viewFull: string; archiveTitle: string; filters: { all: string; photo: string; video: string }; photoLabel: string; videoLabel: string; note: string; showAll: string; showLess: string };
  pricing: { eyebrow: string; title: string; lead: string; factors: FeatureItem[]; offerEyebrow: string; offerTitle: string; offerText: string; responseNote: string; packageName: string; priceNote: string; includes: string[]; cta: string; durationNote: string };
  trust: { eyebrow: string; title: string; stepsLabel: string; proofLabel: string; photoAlt: string; items: FeatureItem[] };
  faq: { eyebrow: string; title: string; items: FaqItem[] };
  reviews: { eyebrow: string; title: string; companies: string[]; eventSizes: string[]; caseLabel: string; emptyTitle: string; emptyText: string; moderationNote: string; badge: string; leaveReview: string; prev: string; next: string; pageOf: string; modalTitle: string; formName: string; formNamePlaceholder: string; formRole: string; formRolePlaceholder: string; formCompany: string; formCompanyPlaceholder: string; formEventType: string; formEventTypes: string[]; formEventSize: string; formEventDate: string; formContact: string; formContactPlaceholder: string; formConsent: string; formRating: string; formText: string; formTextPlaceholder: string; formSubmit: string; formCancel: string; thankYouTitle: string; thankYouText: string; thankYouClose: string; items: ReviewItem[] };
  finalCta: { eyebrow: string; title: string; subtitle: string; telegramCta: string; callLabel: string };
  location: { eyebrow: string; title: string; advantageTitle: string; advantageText: string; addressLabel: string; addressText: string; howToLabel: string; howToText: string; parkingLabel: string; parkingText: string; openInMaps: string };
  footer: { tagline: string; linksTitle: string; contactTitle: string; rights: string };
}

const reviewForm = {
  companies: [], eventSizes: [], items: [], caseLabel: "", badge: "", prev: "", next: "", pageOf: "",
  formRole: "", formRolePlaceholder: "", formCompany: "", formCompanyPlaceholder: "", formEventType: "",
  formEventTypes: [], formEventSize: "", formEventDate: "", formContact: "", formContactPlaceholder: "",
  formConsent: "", formRating: "", formText: "", formTextPlaceholder: "",
} satisfies Partial<Dictionary["reviews"]>;

export const dictionaries: Record<Locale, Dictionary> = {
  ru: {
    nav: { links: ["Программа", "Галерея", "Стоимость", "Почему мы", "Вопросы", "Контакты"], cta: "Получить предложение" },
    hero: {
      eyebrow: "КОРПОРАТИВНЫЙ ДЕНЬ У МОРЯ · STROOMI RAND",
      title: "Ваш корпоративный день у моря.",
      subtitle: "Вы создаёте день для своей команды. Мы берём на себя место, инструкторов, оборудование и безопасную водную программу.",
      ctaPrimary: "Получить предложение", ctaSecondary: "Смотреть формат", phoneLabel: "Быстрый ответ", detailsLabel: "Основная информация",
      details: ["Stroomi rand · Таллинн", "Около 3,5 часов", "RU · EST · ENG"],
    },
    intro: {
      eyebrow: "TIME TO SURF", title: "У каждой компании — свой день",
      paragraphs: [
        "Вы уже знаете, каким видите корпоратив: встреча команды, общение, workshop, гриль или вечер у моря.",
        "Time to Surf отвечает за водную программу: станцию на пляже, подготовку площадки, инструкторов, оборудование и организацию выхода на воду.",
        "Ваш сценарий остаётся за вами. Мы профессионально берём на себя воду.",
      ],
      photoAlts: ["Команда начинает корпоративный день у моря", "Подготовленная станция Time to Surf"],
      photoCaptions: ["День начинается вместе", "Пространство готово к вашему формату"], journeyTitle: "Ваш день у моря",
      journey: [
        { title: "Приезд", desc: "Команда приезжает на станцию — площадка и оборудование уже подготовлены." },
        { title: "Водная программа", desc: "Инструкторы проводят брифинг, выдают экипировку и сопровождают первый выход на воду." },
        { title: "Свободное продолжение", desc: "После активной части вы продолжаете день в своём ритме: общение, еда, музыка или собственная программа." },
      ],
    },
    suitedFor: { title: "Подходит для", items: ["Корпоративных летних дней", "Встреч команд и отделов", "Дней компании", "Собственных HR-программ, workshop и неформальных встреч"] },
    features: {
      eyebrow: "ПРОГРАММА", title: "Как проходит водная программа",
      subtitle: "Средняя продолжительность — около 3,5 часов. Содержание водной части зависит от погоды, ветра, безопасности и состава группы.",
      adaptabilityTitle: "Всегда подстраиваемся под условия", adaptabilityText: "Мы согласуем формат заранее и подбираем активности, подходящие именно для этого дня.",
      stages: ["Встреча", "Брифинг", "Первый опыт", "Практика", "Свободное время", "Завершение"], timelineStart: "Встречаемся на станции", timelineEnd: "Дальше — ваш сценарий",
      items: [
        { title: "Встреча на станции и подготовка", desc: "Знакомимся с группой, объясняем порядок дня, выдаём гидрокостюмы и спасательные жилеты. Всё необходимое для воды уже на месте." },
        { title: "Понятный инструктаж без лишней теории", desc: "Инструкторы рассказывают о правилах, показывают оборудование и готовят участников к первому выходу на воду." },
        { title: "Первый опыт в серфинге", desc: "В зависимости от условий это может быть SUP, windsurf, wing или другой подходящий вариант. Опыт не нужен — задача попробовать безопасно." },
        { title: "Время освоиться и почувствовать воду", desc: "Основная водная часть длится примерно час. Инструкторы остаются рядом, помогают и регулируют темп под участников." },
        { title: "Продолжение по вашему плану", desc: "Если условия позволяют, после основной части можно продолжить практику. Остальные отдыхают на станции, общаются или переходят к своей программе." },
        { title: "Возвращение на станцию", desc: "Снимаем экипировку, делимся впечатлениями и оставляем время для общего фото, еды, музыки или спокойного завершения дня." },
      ],
    },
    gallery: {
      eyebrow: "ГАЛЕРЕЯ", title: "Так выглядит день у моря", subtitle: "Все фотографии и видео Time to Surf.",
      storySubtitle: "Станция, море, оборудование и атмосфера — без постановочных сцен.", storyNote: "Настоящие моменты, из которых складывается общий день команды.",
      curatedCaptions: ["Атмосфера", "Команда", "Станция", "Экипировка", "День у моря"],
      curatedAlts: ["Команда Time to Surf на воде", "Команда с SUP-досками", "Станция Time to Surf", "Подготовленное оборудование", "Корпоративный день у моря"],
      viewFull: "Смотреть всю галерею", archiveTitle: "Все фото и видео", filters: { all: "Все", photo: "Фото", video: "Видео" }, photoLabel: "Фото", videoLabel: "Видео", note: "Фотографии и видео реальных дней на станции Time to Surf.", showAll: "Показать все", showLess: "Свернуть",
    },
    pricing: {
      eyebrow: "СТОИМОСТЬ", title: "Стоимость для вашей команды",
      lead: "Базовый пакет начинается от 350 € и включает до 7 участников. Для больших групп мы рассчитываем количество инструкторов, комплектов экипировки и подходящий формат воды.",
      factors: [
        { title: "Размер группы", desc: "Оптимальный формат — примерно 16–20 человек. При большем составе добавляем инструкторов и оборудование." },
        { title: "Активности", desc: "SUP, windsurf, wing и другие варианты подбираются по погоде, ветру, безопасности и вашим пожеланиям." },
        { title: "Продолжительность", desc: "Базовая водная программа занимает около 3,5 часов. Дополнительный час станции — 80 €." },
        { title: "Дополнения", desc: "Кейтеринг, гриль, фотограф, декор, ведущий или тренер — вы приглашаете специалистов, мы организуем пространство." },
      ],
      offerEyebrow: "ПЕРСОНАЛЬНОЕ ПРЕДЛОЖЕНИЕ", offerTitle: "Рассчитаем формат и стоимость для вашей команды",
      offerText: "Укажите дату, количество участников и как вы планируете провести день. Мы подготовим точное предложение без лишних пакетов.",
      responseNote: "Быстрый ответ. Без обязательств.", packageName: "Предложение включает", priceNote: "Базовый формат от", durationNote: "Точная стоимость после короткого брифа",
      includes: ["Продолжительность и порядок водной части", "Количество инструкторов и комплектов экипировки", "Полный расчёт для группы", "Дополнительные часы и услуги отдельными понятными пунктами"], cta: "Получить предложение",
    },
    trust: {
      eyebrow: "ПОЧЕМУ TIME TO SURF", title: "Почему нам доверяют", stepsLabel: "Доверие строится на опыте, подготовке и ответственности.", proofLabel: "лет работаем у моря", photoAlt: "Команда Time to Surf с оборудованием",
      items: [
        { title: "Работаем у моря с 2013 года", desc: "Проводим занятия, лагеря и групповые мероприятия на воде. Знаем своё дело, местные условия и особенности работы с участниками разного уровня." },
        { title: "Планируем водную часть заранее", desc: "Уточняем размер группы, опыт и пожелания, следим за прогнозом и выбираем подходящие варианты." },
        { title: "Инструкторы отвечают за воду", desc: "Проводим инструктаж, выдаём экипировку, сопровождаем участников и подстраиваем темп под группу." },
        { title: "Проверяем всё до выхода", desc: "Оцениваем погоду и воду, проверяем оборудование и готовность участников. При небезопасных условиях меняем программу." },
      ],
    },
    faq: {
      eyebrow: "FAQ", title: "Часто задаваемые вопросы", items: [
        { q: "Что будет, если погода изменится?", a: "Мы следим за прогнозом до мероприятия и оцениваем условия непосредственно на месте. Если выбранная активность небезопасна или не подходит, заменяем её на доступный формат либо согласуем другое решение. Точный вид активности нельзя гарантировать заранее — безопасность всегда важнее расписания." },
        { q: "Какой размер группы оптимален?", a: "Мы работаем как с небольшими, так и с крупными группами. Наиболее комфортный формат — около 16–20 участников. Группы до 30 человек также возможны: в этом случае увеличиваем количество инструкторов и оборудования." },
        { q: "Требуется ли опыт?", a: "Предыдущий опыт не нужен. Программа рассчитана на первое знакомство с водными видами спорта. Участники получают инструктаж, спасательные жилеты и сопровождение инструкторов. Об особенностях здоровья или неуверенности в воде важно сообщить заранее." },
        { q: "Что нужно взять с собой?", a: "Купальные принадлежности, полотенце, удобную одежду по погоде и сменную обувь. Гидрокостюмы, спасательные жилеты и оборудование для выбранной активности предоставляет Time to Surf." },
        { q: "Можно ли адаптировать программу под нашу компанию?", a: "Да. Вы можете провести собственный workshop, встречу, тренинг, ужин или неформальную программу. Мы согласуем время водной программы и подготовим площадку так, чтобы она вписалась в ваш день." },
        { q: "Что есть на площадке?", a: "Терраса, столы и стулья, мягкие места для отдыха, гамаки, электричество, музыка, гриль и место для костра. Есть раздевалка, рядом находятся туалет, парковка, пляж и море." },
        { q: "Можно ли пригласить дополнительных специалистов?", a: "Да. Вы можете пригласить кейтеринг, повара, фотографа, декоратора, ведущего, тренера или другого специалиста. Мы заранее согласуем размещение и поможем организовать площадку." },
        { q: "На каких языках проходит программа?", a: "Инструктаж и сопровождение доступны на русском, эстонском и английском языках." },
        { q: "Сколько длится программа?", a: "Базовый формат занимает около 3,5 часов, включая подготовку, инструктаж, экипировку и водную часть. Дополнительное время на станции можно заказать отдельно — 80 € за час." },
      ],
    },
    reviews: { ...reviewForm, eyebrow: "ОТЗЫВЫ", title: "Отзывы", emptyTitle: "Здесь будут отзывы компаний, которые уже провели день с нами", emptyText: "Публикуем только реальные отзывы и называем компанию с её разрешения.", moderationNote: "Каждый отзыв проверяется перед публикацией. Нет демонстрационных или выдуманных историй.", leaveReview: "Оставить отзыв", modalTitle: "Оставить отзыв", formName: "Ваше имя", formNamePlaceholder: "Имя", formSubmit: "Отправить", formCancel: "Отмена", thankYouTitle: "Спасибо!", thankYouText: "Отзыв отправлен на проверку.", thankYouClose: "Закрыть" },
    finalCta: { eyebrow: "КОРПОРАТИВНЫЙ ДЕНЬ У МОРЯ", title: "Вы знаете свою команду. Мы знаем воду.", subtitle: "Сообщите дату, количество участников и каким вы видите день. Мы предложим подходящую водную программу и прозрачный расчёт.", telegramCta: "Обсудить программу в Telegram", callLabel: "или позвоните" },
    location: { eyebrow: "МЕСТО ПРОВЕДЕНИЯ", title: "Море ближе, чем кажется", advantageTitle: "Около 20 минут от центра Таллинна", advantageText: "Пляж, море и собственная станция недалеко от города — достаточно близко для удобной логистики и достаточно далеко, чтобы сменить обстановку.", addressLabel: "Адрес", addressText: "Stroomi rand, Tallinn — в конце пляжа, со стороны Rocca al Mare.", howToLabel: "Как добраться", howToText: "Автобусы №40 и 48 до остановки «Stroomi rand». От остановки — короткая прогулка до станции.", parkingLabel: "Парковка", parkingText: "Рядом с пляжем есть бесплатная парковка. В тёплые выходные места заполняются быстрее, поэтому лучше приехать заранее.", openInMaps: "Открыть в Google Maps" },
    footer: { tagline: "Водные активности и корпоративные дни у моря в Таллинне с 2013 года.", linksTitle: "Ссылки", contactTitle: "Контакты", rights: "Все права защищены." },
  },

  et: {
    nav: { links: ["Programm", "Galerii", "Hind", "Miks meie", "Küsimused", "Kontakt"], cta: "Küsi pakkumist" },
    hero: { eyebrow: "ETTEVÕTTE PÄEV MERE ÄÄRES · STROOMI RAND", title: "Teie ettevõtte päev mere ääres.", subtitle: "Teie loote päeva oma meeskonnale. Meie hoolitseme koha, instruktorite, varustuse ja turvalise veeprogrammi eest.", ctaPrimary: "Küsi pakkumist", ctaSecondary: "Vaata formaati", phoneLabel: "Kiire vastus", detailsLabel: "Põhiinfo", details: ["Stroomi rand · Tallinn", "Umbes 3,5 tundi", "RU · EST · ENG"] },
    intro: { eyebrow: "TIME TO SURF", title: "Igal ettevõttel on oma päev", paragraphs: ["Te juba teate, millisena näete oma ettevõtte päeva: meeskonna kohtumine, suhtlemine, workshop, grill või õhtu mere ääres.", "Time to Surf vastutab veeprogrammi eest: rannajaam, ala ettevalmistus, instruktorid, varustus ja turvaline veele minek.", "Teie stsenaarium jääb teie omaks. Meie võtame professionaalselt enda peale vee."], photoAlts: ["Meeskond alustab päeva mere ääres", "Ettevalmistatud Time to Surfi jaam"], photoCaptions: ["Päev algab koos", "Ruum on teie formaadiks valmis"], journeyTitle: "Teie päev mere ääres", journey: [{ title: "Saabumine", desc: "Meeskond saabub jaama — ala ja varustus on juba valmis." }, { title: "Veeprogramm", desc: "Instruktorid teevad briifingu, jagavad varustuse ja saadavad esimest veele minekut." }, { title: "Vaba jätk", desc: "Pärast aktiivset osa jätkate omas tempos: suhtlemine, toit, muusika või teie enda programm." }] },
    suitedFor: { title: "Sobib", items: ["Suvisteks ettevõttepäevadeks", "Tiimide ja osakondade kohtumisteks", "Ettevõtte tähtpäevadeks", "HR-programmideks, workshop'ideks ja vabadeks kohtumisteks"] },
    features: { eyebrow: "PROGRAMM", title: "Kuidas veeprogramm kulgeb", subtitle: "Keskmine kestus on umbes 3,5 tundi. Veeosa sisu sõltub ilmast, tuulest, ohutusest ja grupi koosseisust.", adaptabilityTitle: "Kohandume alati oludega", adaptabilityText: "Lepime formaadi eelnevalt kokku ja valime just sellele päevale sobivad tegevused.", stages: ["Kohtumine", "Briifing", "Esimene kogemus", "Harjutamine", "Vaba aeg", "Lõpetamine"], timelineStart: "Kohtume jaamas", timelineEnd: "Edasi — teie stsenaarium", items: [{ title: "Kohtumine jaamas ja ettevalmistus", desc: "Tutvume grupiga, selgitame päeva kulgu ning jagame kalipsod ja päästevestid. Kõik veeks vajalik on kohal." }, { title: "Selge juhendamine ilma liigse teooriata", desc: "Instruktorid tutvustavad reegleid ja varustust ning valmistavad osalejad ette esimeseks veele minekuks." }, { title: "Esimene surfikogemus", desc: "Oludest sõltuvalt võib see olla SUP, windsurf, wing või muu sobiv variant. Kogemust pole vaja — eesmärk on proovida turvaliselt." }, { title: "Aeg harjuda ja vett tunnetada", desc: "Põhiline veeosa kestab umbes tunni. Instruktorid on lähedal, aitavad ja kohandavad tempot osalejatele." }, { title: "Jätk teie plaani järgi", desc: "Kui olud lubavad, saab pärast põhiosa harjutamist jätkata. Teised puhkavad jaamas, suhtlevad või jätkavad oma programmiga." }, { title: "Tagasi jaama", desc: "Võtame varustuse seljast, jagame muljeid ja jätame aega ühispildiks, söögiks, muusikaks või rahulikuks lõpetuseks." }] },
    gallery: { eyebrow: "GALERII", title: "Selline näeb välja päev mere ääres", subtitle: "Kõik Time to Surfi fotod ja videod.", storySubtitle: "Jaam, meri, varustus ja atmosfäär — ilma lavastatud stseenideta.", storyNote: "Päris hetked, millest kujuneb meeskonna ühine päev.", curatedCaptions: ["Atmosfäär", "Meeskond", "Jaam", "Varustus", "Päev mere ääres"], curatedAlts: ["Time to Surfi meeskond vee peal", "Meeskond SUP-laudadega", "Time to Surfi jaam", "Ettevalmistatud varustus", "Ettevõtte päev mere ääres"], viewFull: "Vaata kogu galeriid", archiveTitle: "Kõik fotod ja videod", filters: { all: "Kõik", photo: "Fotod", video: "Videod" }, photoLabel: "Foto", videoLabel: "Video", note: "Fotod ja videod päris päevadest Time to Surfi jaamas.", showAll: "Näita kõiki", showLess: "Sulge" },
    pricing: { eyebrow: "HIND", title: "Hind teie meeskonnale", lead: "Baaspakett algab 350 eurost ja sisaldab kuni 7 osalejat. Suurematele gruppidele arvutame sobiva instruktorite arvu, varustuskomplektid ja veeformaadi.", factors: [{ title: "Grupi suurus", desc: "Optimaalne formaat on umbes 16–20 inimest. Suurema grupi puhul lisame instruktoreid ja varustust." }, { title: "Tegevused", desc: "SUP, windsurf, wing ja muud variandid valime ilma, tuule, ohutuse ning teie soovide järgi." }, { title: "Kestus", desc: "Veeprogrammi põhiformaat kestab umbes 3,5 tundi. Lisatund jaamas maksab 80 €." }, { title: "Lisad", desc: "Catering, grill, fotograaf, dekoratsioonid, õhtujuht või treener — teie kutsute spetsialistid, meie korraldame ruumi." }], offerEyebrow: "PERSONAALNE PAKKUMINE", offerTitle: "Arvutame teie meeskonnale formaadi ja hinna", offerText: "Saatke kuupäev, osalejate arv ja päeva plaan. Koostame täpse pakkumise ilma tarbetute pakettideta.", responseNote: "Kiire vastus. Kohustusteta.", packageName: "Pakkumine sisaldab", priceNote: "Baaspakett alates", durationNote: "Täpne hind pärast lühikest briifi", includes: ["Veeosa kestus ja järjekord", "Instruktorite ja varustuskomplektide arv", "Täielik grupi hinnakalkulatsioon", "Lisatunnid ja teenused selgete eraldi ridadena"], cta: "Küsi pakkumist" },
    trust: { eyebrow: "MIKS TIME TO SURF", title: "Miks meid usaldatakse", stepsLabel: "Usaldus põhineb kogemusel, ettevalmistusel ja vastutusel.", proofLabel: "aastat mere ääres", photoAlt: "Time to Surfi meeskond varustusega", items: [{ title: "Töötame mere ääres alates 2013. aastast", desc: "Korraldame veetunde, laagreid ja grupiüritusi. Tunneme kohapealseid olusid ja eri tasemega osalejate vajadusi." }, { title: "Planeerime veeosa ette", desc: "Täpsustame grupi suuruse, kogemuse ja soovid, jälgime prognoosi ning valime sobivad variandid." }, { title: "Instruktorid vastutavad vee eest", desc: "Teeme instruktaaži, jagame varustuse, saadame osalejaid ja kohandame tempot grupile." }, { title: "Kontrollime kõike enne veele minekut", desc: "Hindame ilma ja vett ning kontrollime varustust ja osalejate valmisolekut. Ebaturvalistes oludes muudame programmi." }] },
    faq: { eyebrow: "KKK", title: "Korduma kippuvad küsimused", items: [{ q: "Mis juhtub, kui ilm muutub?", a: "Jälgime prognoosi ja hindame tingimusi kohapeal. Kui tegevus pole turvaline või sobiv, asendame selle või lepime kokku muu lahenduse. Täpset tegevust ei saa ette garanteerida — ohutus on alati tähtsam." }, { q: "Milline grupi suurus on optimaalne?", a: "Kõige mugavam formaat on umbes 16–20 osalejat. Võimalikud on ka kuni 30-liikmelised grupid, millele lisame instruktoreid ja varustust." }, { q: "Kas kogemus on vajalik?", a: "Varasemat kogemust pole vaja. Osalejad saavad instruktaaži, päästevestid ja instruktorite toe. Tervislikest eripäradest või ebakindlusest vees palume ette teada anda." }, { q: "Mida kaasa võtta?", a: "Ujumisriided, rätik, ilmale sobivad mugavad riided ja vahetusjalanõud. Kalipsod, päästevestid ja tegevuse varustuse annab Time to Surf." }, { q: "Kas programmi saab meie ettevõttele kohandada?", a: "Jah. Võite korraldada oma workshop'i, kohtumise, koolituse, õhtusöögi või vaba programmi. Sobitame veeosa teie päevaga." }, { q: "Mis on kohapeal olemas?", a: "Terrass, lauad ja toolid, pehmed istumiskohad, võrkkiiged, elekter, muusika, grill ja lõkkekoht. Olemas on riietusruum; lähedal on WC, parkla, rand ja meri." }, { q: "Kas võib kutsuda lisaspetsialiste?", a: "Jah. Võite kutsuda cateringi, koka, fotograafi, dekoraatori, õhtujuhi, treeneri või muu spetsialisti. Lepime paigutuse ette kokku." }, { q: "Mis keeltes programm toimub?", a: "Instruktaaž ja juhendamine on saadaval vene, eesti ja inglise keeles." }, { q: "Kui kaua programm kestab?", a: "Põhiformaat kestab umbes 3,5 tundi koos ettevalmistuse, instruktaaži, varustuse ja veeosaga. Lisatund jaamas maksab 80 €." }] },
    reviews: { ...reviewForm, eyebrow: "TAGASISIDE", title: "Tagasiside", emptyTitle: "Siia tulevad meiega päeva veetnud ettevõtete arvustused", emptyText: "Avaldame ainult päris arvustusi ja nimetame ettevõtte selle loal.", moderationNote: "Iga arvustus kontrollitakse enne avaldamist. Näidis- ega väljamõeldud lugusid ei ole.", leaveReview: "Jäta arvustus", modalTitle: "Jäta arvustus", formName: "Teie nimi", formNamePlaceholder: "Nimi", formSubmit: "Saada", formCancel: "Loobu", thankYouTitle: "Aitäh!", thankYouText: "Arvustus saadeti kontrollimiseks.", thankYouClose: "Sulge" },
    finalCta: { eyebrow: "ETTEVÕTTE PÄEV MERE ÄÄRES", title: "Teie tunnete oma meeskonda. Meie tunneme vett.", subtitle: "Saatke kuupäev, osalejate arv ja oma nägemus päevast. Pakume sobiva veeprogrammi ja läbipaistva hinnakalkulatsiooni.", telegramCta: "Aruta programmi Telegramis", callLabel: "või helista" },
    location: { eyebrow: "ASUKOHT", title: "Meri on lähemal, kui tundub", advantageTitle: "Umbes 20 minutit Tallinna kesklinnast", advantageText: "Rand, meri ja oma jaam linna lähedal — mugav logistika ja piisav vahemaa keskkonna vahetamiseks.", addressLabel: "Aadress", addressText: "Stroomi rand, Tallinn — ranna lõpus, Rocca al Mare poolses otsas.", howToLabel: "Kuidas kohale tulla", howToText: "Bussid 40 ja 48 peatuseni „Stroomi rand“. Peatusest on jaamani lühike jalutuskäik.", parkingLabel: "Parkimine", parkingText: "Ranna kõrval on tasuta parkla. Soojadel nädalavahetustel täitub see kiiremini, seega tasub varem tulla.", openInMaps: "Ava Google Mapsis" },
    footer: { tagline: "Veetegevused ja ettevõttepäevad Tallinnas mere ääres alates 2013. aastast.", linksTitle: "Lingid", contactTitle: "Kontakt", rights: "Kõik õigused kaitstud." },
  },

  en: {
    nav: { links: ["Program", "Gallery", "Pricing", "Why us", "Questions", "Contact"], cta: "Get an offer" },
    hero: { eyebrow: "A CORPORATE DAY BY THE SEA · STROOMI BEACH", title: "Your corporate day by the sea.", subtitle: "You create the day for your team. We take care of the venue, instructors, equipment and a safe water program.", ctaPrimary: "Get an offer", ctaSecondary: "See the format", phoneLabel: "Quick reply", detailsLabel: "Key information", details: ["Stroomi Beach · Tallinn", "About 3.5 hours", "RU · EST · ENG"] },
    intro: { eyebrow: "TIME TO SURF", title: "Every company has its own day", paragraphs: ["You already know what your corporate day should be: a team gathering, conversation, workshop, grill or evening by the sea.", "Time to Surf is responsible for the water program: the beach station, venue setup, instructors, equipment and getting everyone safely onto the water.", "Your plan remains yours. We professionally take care of the water."], photoAlts: ["A team starting its day by the sea", "The prepared Time to Surf station"], photoCaptions: ["The day begins together", "The space is ready for your format"], journeyTitle: "Your day by the sea", journey: [{ title: "Arrival", desc: "The team arrives at the station — the venue and equipment are already prepared." }, { title: "Water program", desc: "Instructors run a briefing, issue equipment and support the first launch onto the water." }, { title: "Your own continuation", desc: "After the active part, continue at your own pace with conversation, food, music or your own program." }] },
    suitedFor: { title: "Ideal for", items: ["Summer corporate days", "Team and department meetings", "Company days", "Your own HR programs, workshops and informal gatherings"] },
    features: { eyebrow: "PROGRAM", title: "How the water program works", subtitle: "Average duration is about 3.5 hours. The water segment depends on weather, wind, safety and group composition.", adaptabilityTitle: "Always adapted to conditions", adaptabilityText: "We agree the format in advance and select activities that fit that particular day.", stages: ["Welcome", "Briefing", "First experience", "Practice", "Free time", "Wrap-up"], timelineStart: "Meet at the station", timelineEnd: "Next — your plan", items: [{ title: "Welcome and preparation at the station", desc: "We meet the group, explain the day, and issue wetsuits and life jackets. Everything needed for the water is ready." }, { title: "Clear instruction without unnecessary theory", desc: "Instructors explain the rules, demonstrate the equipment and prepare everyone for their first launch." }, { title: "A first surfing experience", desc: "Depending on conditions, this may be SUP, windsurf, wing or another suitable option. No experience is needed — the goal is to try safely." }, { title: "Time to settle in and feel the water", desc: "The main water segment lasts about an hour. Instructors stay close, help and adjust the pace to participants." }, { title: "Continue according to your plan", desc: "When conditions allow, participants may keep practising. Others can relax at the station, talk or move on to their own program." }, { title: "Return to the station", desc: "We remove equipment, share impressions and leave time for a group photo, food, music or a relaxed finish." }] },
    gallery: { eyebrow: "GALLERY", title: "What a day by the sea looks like", subtitle: "All Time to Surf photos and videos.", storySubtitle: "The station, sea, equipment and atmosphere — no staged scenes.", storyNote: "Real moments that come together as a shared team day.", curatedCaptions: ["Atmosphere", "Team", "Station", "Equipment", "Day by the sea"], curatedAlts: ["Time to Surf team on the water", "Team with SUP boards", "Time to Surf station", "Prepared water equipment", "Corporate day by the sea"], viewFull: "View full gallery", archiveTitle: "All photos and videos", filters: { all: "All", photo: "Photos", video: "Videos" }, photoLabel: "Photo", videoLabel: "Video", note: "Photos and videos from real days at the Time to Surf station.", showAll: "Show all", showLess: "Collapse" },
    pricing: { eyebrow: "PRICING", title: "Pricing for your team", lead: "The base package starts at €350 and includes up to 7 participants. For larger groups, we calculate the right number of instructors, equipment sets and water format.", factors: [{ title: "Group size", desc: "The ideal format is around 16–20 people. For larger groups, we add instructors and equipment." }, { title: "Activities", desc: "SUP, windsurf, wing and other options are selected around weather, wind, safety and your preferences." }, { title: "Duration", desc: "The base water program takes about 3.5 hours. An additional station hour is €80." }, { title: "Add-ons", desc: "Catering, grill, photographer, décor, host or trainer — you invite the specialists and we organise the space." }], offerEyebrow: "PERSONAL OFFER", offerTitle: "We will calculate the format and price for your team", offerText: "Tell us the date, participant count and how you plan to spend the day. We will prepare an exact offer without unnecessary packages.", responseNote: "Quick reply. No obligation.", packageName: "The offer includes", priceNote: "Base format from", durationNote: "Final price after a short briefing", includes: ["Duration and sequence of the water segment", "Number of instructors and equipment sets", "Full calculation for the group", "Extra hours and services as clear separate items"], cta: "Get an offer" },
    trust: { eyebrow: "WHY TIME TO SURF", title: "Why teams trust us", stepsLabel: "Trust is built on experience, preparation and responsibility.", proofLabel: "years working by the sea", photoAlt: "Time to Surf team with equipment", items: [{ title: "Working by the sea since 2013", desc: "We run lessons, camps and group events on the water. We know the local conditions and how to work with participants of different levels." }, { title: "We plan the water segment in advance", desc: "We confirm group size, experience and wishes, monitor the forecast and select suitable options." }, { title: "Our instructors are responsible for the water", desc: "We brief participants, issue equipment, provide support and adapt the pace to the group." }, { title: "We check everything before launching", desc: "We assess weather and water, inspect equipment and participant readiness. In unsafe conditions, we change the program." }] },
    faq: { eyebrow: "FAQ", title: "Frequently asked questions", items: [{ q: "What happens if the weather changes?", a: "We monitor the forecast and assess conditions on site. If an activity is unsafe or unsuitable, we replace it or agree another solution. A specific activity cannot be guaranteed in advance — safety comes first." }, { q: "What group size works best?", a: "The most comfortable format is around 16–20 participants. Groups of up to 30 are also possible; we add instructors and equipment." }, { q: "Is previous experience required?", a: "No. The program is designed as a first introduction to water sports. Participants receive instruction, life jackets and instructor support. Please tell us in advance about health considerations or uncertainty in water." }, { q: "What should we bring?", a: "Swimwear, a towel, comfortable weather-appropriate clothing and spare shoes. Time to Surf provides wetsuits, life jackets and activity equipment." }, { q: "Can the program be adapted to our company?", a: "Yes. You can run your own workshop, meeting, training, dinner or informal program. We coordinate the water segment and prepare the venue to fit your day." }, { q: "What is available at the venue?", a: "A terrace, tables and chairs, soft seating, hammocks, electricity, music, grill and firepit. There is a changing room, with toilets, parking, beach and sea nearby." }, { q: "Can we invite additional specialists?", a: "Yes. You may bring catering, a chef, photographer, decorator, host, trainer or another specialist. We agree the setup in advance and help organise the space." }, { q: "Which languages are available?", a: "Instruction and support are available in Russian, Estonian and English." }, { q: "How long does the program take?", a: "The base format takes about 3.5 hours, including preparation, briefing, equipment and the water segment. Extra station time is €80 per hour." }] },
    reviews: { ...reviewForm, eyebrow: "REVIEWS", title: "Reviews", emptyTitle: "This is where reviews from companies that spent a day with us will appear", emptyText: "We publish only genuine reviews and name the company with its permission.", moderationNote: "Every review is checked before publication. There are no demo or invented stories.", leaveReview: "Leave a review", modalTitle: "Leave a review", formName: "Your name", formNamePlaceholder: "Name", formSubmit: "Submit", formCancel: "Cancel", thankYouTitle: "Thank you!", thankYouText: "Your review was submitted for verification.", thankYouClose: "Close" },
    finalCta: { eyebrow: "A CORPORATE DAY BY THE SEA", title: "You know your team. We know the water.", subtitle: "Tell us the date, participant count and how you see the day. We will suggest a suitable water program and a transparent calculation.", telegramCta: "Discuss the program on Telegram", callLabel: "or call" },
    location: { eyebrow: "LOCATION", title: "The sea is closer than it seems", advantageTitle: "About 20 minutes from central Tallinn", advantageText: "A beach, the sea and our own station close to the city — near enough for easy logistics and far enough for a change of scene.", addressLabel: "Address", addressText: "Stroomi Beach, Tallinn — at the end of the beach, towards Rocca al Mare.", howToLabel: "Getting here", howToText: "Buses 40 and 48 to the “Stroomi rand” stop. It is a short walk from the stop to the station.", parkingLabel: "Parking", parkingText: "Free parking is available by the beach. It fills faster on warm weekends, so arriving early is recommended.", openInMaps: "Open in Google Maps" },
    footer: { tagline: "Water activities and corporate days by the sea in Tallinn since 2013.", linksTitle: "Links", contactTitle: "Contact", rights: "All rights reserved." },
  },
};
